# Generated by Django 6.0.5 on 2026-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unit_pressure',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_rain',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_temp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_wind',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
