# Generated by Django 6.0.5 on 2026-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_unit_pressure_userprofile_unit_rain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='may_add_stations',
            field=models.BooleanField(default=False, verbose_name='may add their own stations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='station_limit',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='how many'),
        ),
    ]
