# Generated by Django 6.0.5 on 2026-10-01 04:55

import django.db.models.deletion
import weather.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('mac_address', models.CharField(help_text='As shown on the console or ambientweather.net, e.g. 48:3F:DA:12:34:56.', max_length=17, unique=True, validators=[weather.models.validate_mac], verbose_name='MAC address')),
                ('timezone', models.CharField(default='UTC', help_text="IANA name, e.g. America/Denver. Defines the station's local day.", max_length=64, validators=[weather.models.validate_timezone])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True, verbose_name='elevation (m)')),
                ('is_public', models.BooleanField(default=False, help_text="Anyone can view this station's dashboard and charts without signing in.")),
                ('archive_interval_s', models.PositiveIntegerField(default=300, help_text='Pushed readings are merged into buckets of this length. 300 matches ambientweather.net.', verbose_name='archive interval (s)')),
                ('push_token', models.CharField(default=weather.models._new_push_token, editable=False, max_length=64, unique=True)),
                ('push_passkey', models.CharField(blank=True, help_text='Learned from the first accepted upload. Clear it to re-learn.', max_length=64)),
                ('ambient_api_enabled', models.BooleanField(default=True, help_text='Fetch archive records from ambientweather.net (needs AMBIENT_* keys in .env).', verbose_name='poll Ambient API')),
                ('rollup_dirty_from', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LatestReading',
            fields=[
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest', serialize=False, to='weather.station')),
                ('timestamp', models.DateTimeField(help_text='When the console took the reading (UTC).')),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('ambient_push', 'Ambient push'), ('ecowitt_push', 'Ecowitt push'), ('api', 'Ambient API poll'), ('backfill', 'Ambient API backfill'), ('downsampled', 'Downsampled')], max_length=16)),
                ('data', models.JSONField(default=dict, help_text='SI values keyed like Observation columns.')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IngestCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('protocol', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=8)),
                ('remote_addr', models.CharField(blank=True, max_length=45)),
                ('path', models.CharField(max_length=500)),
                ('payload', models.TextField(help_text='Query string or form body.')),
                ('accepted', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='weather.station')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='UTC end of the interval.')),
                ('interval_s', models.PositiveIntegerField(default=300)),
                ('sample_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('ambient_push', 'Ambient push'), ('ecowitt_push', 'Ecowitt push'), ('api', 'Ambient API poll'), ('backfill', 'Ambient API backfill'), ('downsampled', 'Downsampled')], max_length=16)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('dewpoint_c', models.FloatField(blank=True, null=True)),
                ('pressure_rel_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_abs_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_gust_ms', models.FloatField(blank=True, null=True)),
                ('wind_dir_deg', models.FloatField(blank=True, null=True)),
                ('rain_rate_mmh', models.FloatField(blank=True, null=True)),
                ('rain_event_mm', models.FloatField(blank=True, null=True)),
                ('rain_daily_mm', models.FloatField(blank=True, null=True)),
                ('rain_counter_mm', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('solar_wm2', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('temp_in_c', models.FloatField(blank=True, null=True)),
                ('humidity_in', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('pressure_min_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_max_hpa', models.FloatField(blank=True, null=True)),
                ('solar_max_wm2', models.FloatField(blank=True, null=True)),
                ('uv_max', models.FloatField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional sensors and console fields, keyed by their upload names.')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.station')),
            ],
            options={
                'ordering': ['station', 'timestamp'],
                'constraints': [models.UniqueConstraint(fields=('station', 'timestamp'), name='uniq_observation_station_timestamp')],
            },
        ),
    ]
