# Generated by Django 6.0.5 on 2026-10-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('covered_s', models.PositiveIntegerField(default=0, help_text='Seconds of the period with observations.')),
                ('coverage', models.FloatField(default=0, help_text='covered_s / period length (0–1).')),
                ('temp_avg_c', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_avg', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('dewpoint_avg_c', models.FloatField(blank=True, null=True)),
                ('dewpoint_min_c', models.FloatField(blank=True, null=True)),
                ('dewpoint_max_c', models.FloatField(blank=True, null=True)),
                ('pressure_avg_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_min_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_max_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_avg_ms', models.FloatField(blank=True, null=True)),
                ('wind_speed_max_ms', models.FloatField(blank=True, null=True)),
                ('wind_gust_max_ms', models.FloatField(blank=True, null=True)),
                ('wind_dir_avg_deg', models.FloatField(blank=True, help_text='Speed-weighted vector mean; NULL when calm.', null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('rain_rate_max_mmh', models.FloatField(blank=True, null=True)),
                ('solar_avg_wm2', models.FloatField(blank=True, null=True)),
                ('solar_max_wm2', models.FloatField(blank=True, null=True)),
                ('uv_avg', models.FloatField(blank=True, null=True)),
                ('uv_max', models.FloatField(blank=True, null=True)),
                ('temp_in_avg_c', models.FloatField(blank=True, null=True)),
                ('temp_in_min_c', models.FloatField(blank=True, null=True)),
                ('temp_in_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_in_avg', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='weather.station')),
            ],
            options={
                'ordering': ['station', 'date'],
                'constraints': [models.UniqueConstraint(fields=('station', 'date'), name='uniq_daily_station_date')],
            },
        ),
        migrations.CreateModel(
            name='HourlyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('covered_s', models.PositiveIntegerField(default=0, help_text='Seconds of the period with observations.')),
                ('coverage', models.FloatField(default=0, help_text='covered_s / period length (0–1).')),
                ('temp_avg_c', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_avg', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('dewpoint_avg_c', models.FloatField(blank=True, null=True)),
                ('dewpoint_min_c', models.FloatField(blank=True, null=True)),
                ('dewpoint_max_c', models.FloatField(blank=True, null=True)),
                ('pressure_avg_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_min_hpa', models.FloatField(blank=True, null=True)),
                ('pressure_max_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_avg_ms', models.FloatField(blank=True, null=True)),
                ('wind_speed_max_ms', models.FloatField(blank=True, null=True)),
                ('wind_gust_max_ms', models.FloatField(blank=True, null=True)),
                ('wind_dir_avg_deg', models.FloatField(blank=True, help_text='Speed-weighted vector mean; NULL when calm.', null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('rain_rate_max_mmh', models.FloatField(blank=True, null=True)),
                ('solar_avg_wm2', models.FloatField(blank=True, null=True)),
                ('solar_max_wm2', models.FloatField(blank=True, null=True)),
                ('uv_avg', models.FloatField(blank=True, null=True)),
                ('uv_max', models.FloatField(blank=True, null=True)),
                ('temp_in_avg_c', models.FloatField(blank=True, null=True)),
                ('temp_in_min_c', models.FloatField(blank=True, null=True)),
                ('temp_in_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_in_avg', models.FloatField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='weather.station')),
            ],
            options={
                'ordering': ['station', 'period_start'],
                'constraints': [models.UniqueConstraint(fields=('station', 'period_start'), name='uniq_hourly_station_period')],
            },
        ),
    ]
