# Generated by Django 6.0.5 on 2026-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_dailyrollup_hourlyrollup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrollup',
            name='rain_coverage',
            field=models.FloatField(default=0, help_text='Fraction of the period with a rain amount.'),
        ),
        migrations.AddField(
            model_name='dailyrollup',
            name='temp_coverage',
            field=models.FloatField(default=0, help_text='Fraction of the period with outdoor temperature.'),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='rain_coverage',
            field=models.FloatField(default=0, help_text='Fraction of the period with a rain amount.'),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='temp_coverage',
            field=models.FloatField(default=0, help_text='Fraction of the period with outdoor temperature.'),
        ),
    ]
