# Generated by Django 6.0.5 on 2026-10-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rollup_sensor_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='place',
            field=models.CharField(blank=True, help_text='Shown under the name, e.g. "Boulder, Colorado".', max_length=100),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='WS4Free', help_text='Shown in the header and browser tab, e.g. "Mesa Ridge Weather".', max_length=60)),
                ('tagline', models.CharField(blank=True, help_text='One line under the title on the dashboard.', max_length=140)),
                ('about', models.TextField(blank=True, help_text='A few sentences about the station and site, shown to visitors.')),
                ('default_station', models.ForeignKey(blank=True, help_text="Shown at the site's home page when there is more than one station.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weather.station')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
