# Generated by Django 6.0.5 on 2026-10-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_station_place_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, help_text='Blank = still ongoing; new readings are excluded too.', null=True)),
                ('groups', models.JSONField(help_text='Keys of EXCLUSION_GROUPS.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('readings', models.PositiveIntegerField(default=0, help_text='Readings affected when last applied.')),
                ('status', models.CharField(choices=[('pending', 'Applying'), ('applied', 'Applied'), ('removing', 'Removing'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='weather.station')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_values', to='weather.observation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('observation', 'field'), name='uniq_excluded_observation_field')],
            },
        ),
    ]
