# Generated by Django 6.0.5 on 2026-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_data_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='anemometer_height_m',
            field=models.FloatField(default=2.0, help_text='Height of the wind sensor above the ground; used to adjust wind for evapotranspiration.', verbose_name='anemometer height (m)'),
        ),
    ]
