# Generated by Django 6.0.5 on 2026-10-01 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_anemometer_height'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('reference', 'Fitted to a reference station'), ('manual', 'Manual')], max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, help_text='Blank = still ongoing; new readings are corrected too.', null=True)),
                ('coefficients', models.JSONField(blank=True, default=dict, help_text='{"1": {"night": °C, "day": °C, "solar": °C per 1000 W/m²}, … "12": …}')),
                ('reference_station', models.CharField(blank=True, help_text='Airport/ASOS identifier, e.g. DEN.', max_length=10)),
                ('baseline_start', models.DateField(blank=True, null=True)),
                ('baseline_end', models.DateField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, help_text='Progress or the reason a fit failed.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('fitting', 'Fitting'), ('fitted', 'Ready to review'), ('pending', 'Applying'), ('applied', 'Applied'), ('removing', 'Removing'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('readings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='weather.station')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='CalibratedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrated_values', to='weather.observation')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originals', to='weather.tempcalibration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('observation', 'field'), name='uniq_calibrated_observation_field')],
            },
        ),
    ]
