# Generated by Django 6.0.5 on 2026-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_temperature_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrollup',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra sensors: {upload key: [mean, min, max]} in SI units.'),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra sensors: {upload key: [mean, min, max]} in SI units.'),
        ),
        migrations.AddField(
            model_name='station',
            name='rain_gauge',
            field=models.CharField(choices=[('auto', 'Automatic'), ('tipping', 'Tipping-bucket gauge'), ('piezo', 'Piezo (haptic) sensor')], default='auto', help_text='Which rain sensor to record when the console reports two (e.g. an Ecowitt WS90 plus a tipping-bucket gauge). Automatic prefers the tipping bucket. Applies to new uploads.', max_length=8),
        ),
        migrations.AddField(
            model_name='station',
            name='sensors',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Extra sensors seen in uploads, keyed by upload name: {"name": "...", "public": bool}.'),
        ),
    ]
