# Generated by Django 6.0.5 on 2026-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_extra_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short line shown beside the site title in the header, e.g. "Backyard weather since 2021".', max_length=140),
        ),
    ]
