# Generated by Django 6.0.5 on 2026-10-02 19:03

from django.db import migrations, models


def resummarise_history(apps, schema_editor):
    """Wind chill and heat index are new summary values: let the rollup job
    recompute every station's whole history once, in the background."""
    Station = apps.get_model('weather', 'Station')
    Observation = apps.get_model('weather', 'Observation')
    for station in Station.objects.all():
        first = Observation.objects.filter(station=station).order_by('timestamp').values_list('timestamp', flat=True).first()
        if first is not None:
            Station.objects.filter(pk=station.pk).update(rollup_dirty_from=first)


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_tagline_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrollup',
            name='heatindex_max_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrollup',
            name='windchill_min_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='heatindex_max_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='windchill_min_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(resummarise_history, migrations.RunPython.noop),
    ]
