# Generated by Django 6.0.5 on 2026-10-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_apparent_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationForecast',
            fields=[
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='forecast', serialize=False, to='weather.station')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When `days` was last fetched successfully.', null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('days', models.JSONField(blank=True, default=list, help_text='[{date, code, high_c, low_c, rain_pct, rain_mm}, …], SI units.')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='forecast_enabled',
            field=models.BooleanField(default=True, help_text="Show a daily forecast from Open-Meteo on the dashboard. Sends the station's approximate location (rounded to about 1 km) to open-meteo.com.", verbose_name='show forecast'),
        ),
    ]
