# Generated by Django 6.0.5 on 2026-10-04 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_forecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(help_text='UTC. Local midnight when no time was given.')),
                ('has_time', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('moved', 'Moved'), ('sensor', 'Sensor replaced'), ('maintenance', 'Maintenance'), ('battery', 'Battery changed'), ('outage', 'Outage'), ('other', 'Other')], default='other', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visitors see public entries on the charts; private ones only you see.', verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='weather.station')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
