# Generated by Django 6.0.5 on 2026-10-04 14:01

import weather.models
from django.db import migrations, models


def guess_source(apps, schema_editor):
    """Existing stations were all set up as Ambient stations; one whose newest
    readings arrive as Ecowitt uploads is really an Ecowitt station."""
    Station = apps.get_model('weather', 'Station')
    Observation = apps.get_model('weather', 'Observation')
    for station in Station.objects.all():
        latest = (Observation.objects.filter(station=station).order_by('-timestamp')
                  .values_list('source', flat=True).first())
        if latest == 'ecowitt_push':
            Station.objects.filter(pk=station.pk).update(source='ecowitt')


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_station_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='source',
            field=models.CharField(choices=[('ambient', 'Ambient Weather console'), ('ecowitt', 'Ecowitt or Fine Offset console'), ('weewx', 'WeeWX'), ('other', 'Other (Wunderground-style uploads)')], default='ambient', help_text='Decides which setup instructions and settings apply. Uploads in any supported format are accepted.', max_length=10, verbose_name='readings come from'),
        ),
        migrations.AlterField(
            model_name='latestreading',
            name='source',
            field=models.CharField(choices=[('ambient_push', 'Ambient push'), ('ecowitt_push', 'Ecowitt push'), ('api', 'Ambient API poll'), ('backfill', 'Ambient API backfill'), ('downsampled', 'Downsampled'), ('weewx_import', 'WeeWX import')], max_length=16),
        ),
        migrations.AlterField(
            model_name='observation',
            name='source',
            field=models.CharField(choices=[('ambient_push', 'Ambient push'), ('ecowitt_push', 'Ecowitt push'), ('api', 'Ambient API poll'), ('backfill', 'Ambient API backfill'), ('downsampled', 'Downsampled'), ('weewx_import', 'WeeWX import')], max_length=16),
        ),
        migrations.AlterField(
            model_name='station',
            name='mac_address',
            field=models.CharField(blank=True, help_text='As shown on the console or ambientweather.net, e.g. 48:3F:DA:12:34:56. Needed for the Ambient Weather API; optional otherwise.', max_length=17, null=True, unique=True, validators=[weather.models.validate_mac], verbose_name='MAC address'),
        ),
        migrations.RunPython(guess_source, migrations.RunPython.noop),
    ]
