# Generated by Django 6.0.5 on 2026-10-04 14:14

from django.db import migrations, models


def resummarise_history(apps, schema_editor):
    """Low-battery periods are a new summary value: rebuild every station's history
    once, in the background (the rollup job picks this up)."""
    Station = apps.get_model('weather', 'Station')
    Observation = apps.get_model('weather', 'Observation')
    for station in Station.objects.all():
        first = Observation.objects.filter(station=station).order_by('timestamp').values_list('timestamp', flat=True).first()
        if first is not None:
            Station.objects.filter(pk=station.pk).update(rollup_dirty_from=first)


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_station_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrollup',
            name='low_batteries',
            field=models.JSONField(blank=True, default=list, help_text='Sensors whose battery the console reported low during the period.'),
        ),
        migrations.AddField(
            model_name='hourlyrollup',
            name='low_batteries',
            field=models.JSONField(blank=True, default=list, help_text='Sensors whose battery the console reported low during the period.'),
        ),
        migrations.RunPython(resummarise_history, migrations.RunPython.noop),
    ]
