# Generated by Django 6.0.5 on 2026-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_low_batteries'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationforecast',
            name='hours',
            field=models.JSONField(blank=True, default=list, help_text='[{time, code, temp_c, feels_c, humidity, rain_pct, rain_mm, …}, …], station-local times, SI units.'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='days',
            field=models.JSONField(blank=True, default=list, help_text='[{date, code, high_c, low_c, rain_pct, rain_mm, wind_ms, …}, …], SI units.'),
        ),
    ]
