# Generated by Django 6.0.5 on 2026-10-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_forecast_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wu_id', models.CharField(max_length=32, verbose_name='Weather Underground station ID')),
                ('label', models.CharField(blank=True, help_text='Its neighbourhood, as Weather Underground names it.', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('include', models.BooleanField(default=True, help_text='Count it in the comparison. Turn off a station that reads oddly.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, help_text='When it last returned a reading.', null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbours', to='weather.station')),
            ],
            options={
                'ordering': ['wu_id'],
            },
        ),
        migrations.CreateModel(
            name='NeighbourReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('dewpoint_c', models.FloatField(blank=True, null=True)),
                ('qc_status', models.SmallIntegerField(blank=True, help_text="Weather Underground's quality check: 1 passed, -1 failed.", null=True)),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weather.neighbour')),
            ],
        ),
        migrations.AddConstraint(
            model_name='neighbour',
            constraint=models.UniqueConstraint(fields=('station', 'wu_id'), name='uniq_neighbour_station_wu_id'),
        ),
        migrations.AddIndex(
            model_name='neighbourreading',
            index=models.Index(fields=['timestamp'], name='weather_nei_timesta_4eb150_idx'),
        ),
        migrations.AddConstraint(
            model_name='neighbourreading',
            constraint=models.UniqueConstraint(fields=('neighbour', 'timestamp'), name='uniq_neighbour_reading'),
        ),
    ]
