# Generated by Django 6.0.5 on 2026-10-04 19:36

import django.db.models.deletion
import weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_neighbours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sensor gateway', max_length=60)),
                ('push_token', models.CharField(default=weather.models._new_push_token, editable=False, max_length=64, unique=True)),
                ('push_passkey', models.CharField(blank=True, help_text='Learned from its first upload.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('latest_extra', models.JSONField(blank=True, default=dict, help_text='The extra sensors in its newest upload (raw).')),
                ('latest_at', models.DateTimeField(blank=True, help_text='When its newest upload was taken.', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='weather.station')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
