# Generated by Django 6.0.5 on 2026-10-07 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_sensor_gateways'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visitors see public entries on the charts; private ones only people with access to the station see.', verbose_name='public'),
        ),
        migrations.CreateModel(
            name='StationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('manager', 'Manager')], default='viewer', max_length=8)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='weather.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('station', 'user'), name='unique_station_access')],
            },
        ),
    ]
