# Generated by Django 6.0.5 on 2026-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_station_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('advanced', 'Advanced viewer'), ('manager', 'Manager')], default='viewer', max_length=10),
        ),
    ]
