# Generated by Django 6.0.5 on 2026-10-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_advanced_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcalibration',
            name='mode',
            field=models.CharField(choices=[('reference', 'Fitted to a reference station'), ('neighbours', 'Fitted to neighbours'), ('manual', 'Manual')], max_length=10),
        ),
    ]
